[CmdletBinding()]
param(
    [string]$TenantId,
    [string]$BrokerAppName = "servicenow-mcp-obo-broker",
    [string]$InteractiveClientAppName = "servicenow-mcp-obo-interactive-client",
    [string]$BrokerScopeName = "user_impersonation",
    [string]$BrokerIdentifierUri,
    [string]$DownstreamApiAppName = "servicenow-mcp-obo-downstream-api",
    [string]$DownstreamScopeName = "user_impersonation",
    [string]$DownstreamIdentifierUri,
    [string]$CopilotStudioClientAppName = "servicenow-mcp-copilot-studio-client",
    [Alias("CopilotStudioRedirectUri")][string[]]$CopilotStudioRedirectUris,
    [int]$SecretYears = 1,
    [switch]$ConfigureAzdEnvironment,
    [switch]$RotateSecrets,
    [string]$LocalEnvFile = ".env"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function ConvertFrom-AzdEnvironmentValue {
    param([Parameter(Mandatory = $true)][string]$Value)

    $trimmedValue = $Value.Trim()
    if ($trimmedValue.StartsWith('"') -and $trimmedValue.EndsWith('"')) {
        try {
            return ConvertFrom-Json -InputObject $trimmedValue
        } catch {
            throw "Could not decode a quoted value from the active azd environment."
        }
    }
    return $trimmedValue
}

function Assert-AzCli {
    if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
        throw "Azure CLI is required. Install it first: https://aka.ms/azure-cli"
    }
}

function Assert-AzLogin {
    try {
        az account show --output none 2>$null
    } catch {
        throw "You must sign in first. Run: az login"
    }
}

function Assert-AzdCli {
    if (-not (Get-Command azd -ErrorAction SilentlyContinue)) {
        throw "Azure Developer CLI is required for -ConfigureAzdEnvironment. Install it first: https://aka.ms/azd"
    }
}

function Get-AzdEnvironmentValues {
    $values = @{}
    if (-not [string]::IsNullOrWhiteSpace($env:AZURE_ENV_NAME)) {
        foreach ($entry in Get-ChildItem Env:) {
            $values[$entry.Name] = $entry.Value
        }
        return $values
    }

    $rawValues = azd env get-values
    if ($LASTEXITCODE -ne 0) {
        throw "Could not read the active azd environment. Run 'azd env new <name>' first."
    }

    foreach ($line in $rawValues) {
        if ($line -match '^([^=]+)=(.*)$') {
            $values[$matches[1]] = ConvertFrom-AzdEnvironmentValue -Value $matches[2]
        }
    }

    return $values
}

function Set-AzdEnvironmentValues {
    param([Parameter(Mandatory = $true)][hashtable]$Values)

    foreach ($entry in $Values.GetEnumerator()) {
        azd env set $entry.Key $entry.Value | Out-Null
        if ($LASTEXITCODE -ne 0) {
            throw "Failed to set azd environment value: $($entry.Key)"
        }
        Write-Host "Configured azd environment value: $($entry.Key)"
    }
}

function Update-LocalEnvFile {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][hashtable]$Values
    )

    $lines = @(if (Test-Path -Path $Path) { Get-Content -Path $Path } else { @() })
    $seen = @{}

    for ($index = 0; $index -lt $lines.Count; $index++) {
        $line = $lines[$index]
        if ($line.TrimStart().StartsWith("#") -or $line.IndexOf("=") -lt 1) {
            continue
        }

        $key = $line.Substring(0, $line.IndexOf("=")).Trim()
        if ($Values.ContainsKey($key)) {
            $lines[$index] = "$key=$($Values[$key])"
            $seen[$key] = $true
        }
    }

    $missingKeys = @($Values.Keys | Where-Object { -not $seen.ContainsKey($_) } | Sort-Object)
    if ($missingKeys.Count -gt 0) {
        if ($lines.Count -gt 0 -and -not [string]::IsNullOrWhiteSpace($lines[-1])) {
            $lines += ""
        }
        $lines += "# Copilot Studio OAuth settings (generated by azd preprovision)"
        foreach ($key in $missingKeys) {
            $lines += "$key=$($Values[$key])"
        }
    }

    Set-Content -Path $Path -Value $lines -Encoding UTF8
    Write-Host "Updated generated OAuth settings in: $Path"
}

function Get-AppByDisplayName {
    param([Parameter(Mandatory = $true)][string]$DisplayName)

    $raw = az ad app list --display-name $DisplayName --query "[0]" --output json
    if ([string]::IsNullOrWhiteSpace($raw) -or $raw.Trim() -eq "null") {
        return $null
    }

    return ($raw | ConvertFrom-Json)
}

function Ensure-App {
    param([Parameter(Mandatory = $true)][string]$DisplayName)

    $app = Get-AppByDisplayName -DisplayName $DisplayName
    if ($null -ne $app) {
        Write-Host "Reusing existing app registration: $DisplayName ($($app.appId))"
        return $app
    }

    Write-Host "Creating app registration: $DisplayName"
    $created = az ad app create --display-name $DisplayName --sign-in-audience "AzureADMyOrg" --output json | ConvertFrom-Json
    return $created
}

function Ensure-ServicePrincipal {
    param([Parameter(Mandatory = $true)][string]$AppId)

    try {
        az ad sp show --id $AppId --output none 2>$null
        Write-Host "Service principal exists for appId: $AppId"
    } catch {
        Write-Host "Creating service principal for appId: $AppId"
        az ad sp create --id $AppId --output none
    }
}

function Configure-ApiScope {
    param(
        [Parameter(Mandatory = $true)]$App,
        [Parameter(Mandatory = $true)][string]$IdentifierUri,
        [Parameter(Mandatory = $true)][string]$ScopeName
    )

    $appDetailRaw = az rest --method GET --uri "https://graph.microsoft.com/v1.0/applications/$($App.id)" --output json
    $appDetail = $appDetailRaw | ConvertFrom-Json
    $existingScopes = @()
    if ($null -ne $appDetail.api -and $null -ne $appDetail.api.oauth2PermissionScopes) {
        $existingScopes = @($appDetail.api.oauth2PermissionScopes)
    }

    $matchingScope = $existingScopes | Where-Object { $_.value -eq $ScopeName } | Select-Object -First 1
    $identifierUris = @()
    if ($null -ne $appDetail.identifierUris) {
        $identifierUris = @($appDetail.identifierUris)
    }

    if ($matchingScope -and ($identifierUris -contains $IdentifierUri)) {
        Write-Host "Scope '$ScopeName' already configured on $IdentifierUri"
        return $matchingScope.id
    }

    $scopeId = if ($matchingScope) { $matchingScope.id } else { [Guid]::NewGuid().ToString() }
    $scopesForPatch = @()
    if ($matchingScope) {
        $scopesForPatch = $existingScopes
    } else {
        $scopesForPatch = @($existingScopes)
        $scopesForPatch += @{
            id = $scopeId
            value = $ScopeName
            type = "User"
            isEnabled = $true
            adminConsentDisplayName = "Access $ScopeName"
            adminConsentDescription = "Allow the app to access this API on behalf of the signed-in user."
            userConsentDisplayName = "Access $ScopeName"
            userConsentDescription = "Allow the app to access this API on your behalf."
        }
    }

    $patchBody = @{
        identifierUris = @($IdentifierUri)
        api = @{
            requestedAccessTokenVersion = 2
            oauth2PermissionScopes = @($scopesForPatch)
        }
    } | ConvertTo-Json -Depth 10 -Compress

    $tempBodyPath = Join-Path -Path ([System.IO.Path]::GetTempPath()) -ChildPath ("servicenow-mcp-graph-patch-" + [Guid]::NewGuid().ToString() + ".json")
    Set-Content -Path $tempBodyPath -Value $patchBody -Encoding UTF8

    try {
        Write-Host "Configuring API scope '$ScopeName' on $IdentifierUri"
        az rest --method PATCH --uri "https://graph.microsoft.com/v1.0/applications/$($App.id)" --headers "Content-Type=application/json" --body "@$tempBodyPath" --output none
    } finally {
        Remove-Item -Path $tempBodyPath -Force -ErrorAction SilentlyContinue
    }

    return $scopeId
}

function Configure-OptionalClaims {
    param(
        [Parameter(Mandatory = $true)]$App,
        [Parameter(Mandatory = $true)][string]$Label
    )

    # Emit the delegated user's identity claims on both the access token (which the MCP
    # server validates, aud = this app) and the id token. preferred_username is a default
    # v2 claim; email/upn are only present when requested here (and when set on the user).
    $claims = @(
        @{ name = "preferred_username"; essential = $false; additionalProperties = @() },
        @{ name = "email"; essential = $false; additionalProperties = @() },
        @{ name = "upn"; essential = $false; additionalProperties = @() }
    )

    $patchBody = @{
        optionalClaims = @{
            idToken     = $claims
            accessToken = $claims
            saml2Token  = @()
        }
    } | ConvertTo-Json -Depth 10 -Compress

    $tempBodyPath = Join-Path -Path ([System.IO.Path]::GetTempPath()) -ChildPath ("servicenow-mcp-claims-patch-" + [Guid]::NewGuid().ToString() + ".json")
    Set-Content -Path $tempBodyPath -Value $patchBody -Encoding UTF8

    try {
        Write-Host "Configuring optional claims (preferred_username, email, upn) on $Label"
        az rest --method PATCH --uri "https://graph.microsoft.com/v1.0/applications/$($App.id)" --headers "Content-Type=application/json" --body "@$tempBodyPath" --output none
    } finally {
        Remove-Item -Path $tempBodyPath -Force -ErrorAction SilentlyContinue
    }
}

function Grant-DelegatedPermission {
    param(
        [Parameter(Mandatory = $true)][string]$ClientAppId,
        [Parameter(Mandatory = $true)][string]$ResourceAppId,
        [Parameter(Mandatory = $true)][string]$ScopeId,
        [Parameter(Mandatory = $true)][string]$ScopeName,
        [Parameter(Mandatory = $true)][string]$ClientLabel
    )

    $clientApp = az ad app show --id $ClientAppId --output json | ConvertFrom-Json
    $resourceAccess = @($clientApp.requiredResourceAccess) |
        Where-Object { $_.resourceAppId -eq $ResourceAppId } |
        Select-Object -First 1
    $matchingPermission = @($resourceAccess.resourceAccess) |
        Where-Object {
            $_.PSObject.Properties["id"] -and
            $_.PSObject.Properties["type"] -and
            $_.id -eq $ScopeId -and
            $_.type -eq "Scope"
        } |
        Select-Object -First 1
    $permissionExists = $null -ne $matchingPermission

    if ($permissionExists) {
        Write-Host "Delegated permission already configured for $ClientLabel."
    } else {
        Write-Host "Adding delegated permission to $ClientLabel."
        az ad app permission add --id $ClientAppId --api $ResourceAppId --api-permissions "$ScopeId=Scope" --output none
        if ($LASTEXITCODE -ne 0) {
            throw "Could not add delegated permission for $ClientLabel."
        }
    }

    az ad app permission grant --id $ClientAppId --api $ResourceAppId --scope $ScopeName --output none

    try {
        az ad app permission admin-consent --id $ClientAppId --output none
        Write-Host "Admin consent granted for $ClientLabel."
    } catch {
        Write-Warning "Admin consent could not be granted automatically. A tenant admin may need to run: az ad app permission admin-consent --id $ClientAppId"
    }
}

function Set-AppAsPublicClient {
    param([Parameter(Mandatory = $true)][string]$AppId)

    Write-Host "Enabling public client fallback for appId: $AppId"
    az ad app update --id $AppId --is-fallback-public-client true --public-client-redirect-uris "http://localhost" --output none
}

function Configure-WebRedirectUri {
    param(
        [Parameter(Mandatory = $true)][string]$AppObjectId,
        [Parameter(Mandatory = $true)][string]$RedirectUri
    )

    $appDetail = az rest --method GET --uri "https://graph.microsoft.com/v1.0/applications/$AppObjectId" --output json | ConvertFrom-Json
    $redirectUris = @()
    if ($null -ne $appDetail.web -and $null -ne $appDetail.web.redirectUris) {
        $redirectUris = @($appDetail.web.redirectUris)
    }

    if ($redirectUris -contains $RedirectUri) {
        Write-Host "Copilot Studio redirect URI already configured."
        return
    }

    $redirectUris += $RedirectUri
    Write-Host "Adding Copilot Studio web redirect URI."
    az ad app update --id $AppObjectId --web-redirect-uris $redirectUris --output none
}

function Get-OrCreateClientSecret {
    param(
        [Parameter(Mandatory = $true)][string]$AppId,
        [Parameter(Mandatory = $true)][string]$DisplayName,
        [Parameter(Mandatory = $true)][int]$Years,
        [string]$ExistingSecret,
        [switch]$Rotate
    )

    if (-not $Rotate -and -not [string]::IsNullOrWhiteSpace($ExistingSecret)) {
        Write-Host "Reusing the existing $DisplayName secret from the active azd environment."
        return $ExistingSecret
    }

    Write-Host "Creating a new $DisplayName client secret."
    $cred = az ad app credential reset --id $AppId --append --display-name $DisplayName --years $Years --output json | ConvertFrom-Json
    return $cred.password
}

Assert-AzCli
Assert-AzLogin

$azdValues = @{}
if ($ConfigureAzdEnvironment) {
    Assert-AzdCli
    $azdValues = Get-AzdEnvironmentValues
}

if ([string]::IsNullOrWhiteSpace($TenantId)) {
    $TenantId = az account show --query tenantId --output tsv
}

if ([string]::IsNullOrWhiteSpace($TenantId)) {
    throw "Could not resolve tenant ID. Pass -TenantId explicitly."
}

$brokerApp = Ensure-App -DisplayName $BrokerAppName
$interactiveClientApp = Ensure-App -DisplayName $InteractiveClientAppName
$downstreamApp = Ensure-App -DisplayName $DownstreamApiAppName
$copilotStudioClientApp = Ensure-App -DisplayName $CopilotStudioClientAppName

Ensure-ServicePrincipal -AppId $brokerApp.appId
Ensure-ServicePrincipal -AppId $interactiveClientApp.appId
Ensure-ServicePrincipal -AppId $downstreamApp.appId
Ensure-ServicePrincipal -AppId $copilotStudioClientApp.appId

Set-AppAsPublicClient -AppId $interactiveClientApp.appId

if ([string]::IsNullOrWhiteSpace($BrokerIdentifierUri)) {
    $BrokerIdentifierUri = "api://$($brokerApp.appId)"
}

if ([string]::IsNullOrWhiteSpace($DownstreamIdentifierUri)) {
    $DownstreamIdentifierUri = "api://$($downstreamApp.appId)"
}

$brokerScopeId = Configure-ApiScope -App $brokerApp -IdentifierUri $BrokerIdentifierUri -ScopeName $BrokerScopeName
$downstreamScopeId = Configure-ApiScope -App $downstreamApp -IdentifierUri $DownstreamIdentifierUri -ScopeName $DownstreamScopeName

Configure-OptionalClaims -App $brokerApp -Label "broker app"

Grant-DelegatedPermission -ClientAppId $brokerApp.appId -ResourceAppId $downstreamApp.appId -ScopeId $downstreamScopeId -ScopeName $DownstreamScopeName -ClientLabel "broker app"
Grant-DelegatedPermission -ClientAppId $interactiveClientApp.appId -ResourceAppId $brokerApp.appId -ScopeId $brokerScopeId -ScopeName $BrokerScopeName -ClientLabel "interactive client app"
Grant-DelegatedPermission -ClientAppId $copilotStudioClientApp.appId -ResourceAppId $brokerApp.appId -ScopeId $brokerScopeId -ScopeName $BrokerScopeName -ClientLabel "Copilot Studio client app"

if (($null -eq $CopilotStudioRedirectUris -or $CopilotStudioRedirectUris.Count -eq 0) -and $azdValues.ContainsKey("COPILOT_STUDIO_REDIRECT_URI")) {
    $CopilotStudioRedirectUris = @($azdValues["COPILOT_STUDIO_REDIRECT_URI"])
}

if ($null -ne $CopilotStudioRedirectUris -and $CopilotStudioRedirectUris.Count -gt 0) {
    foreach ($redirectUri in @($CopilotStudioRedirectUris | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -Unique)) {
        Configure-WebRedirectUri -AppObjectId $copilotStudioClientApp.id -RedirectUri $redirectUri
    }
} else {
    Write-Warning "Copilot Studio callback URI is not available. Configure POWER_PLATFORM_PAC_PROFILE after Copilot Studio creates the connector, then rerun azd up."
}

$existingBrokerSecret = if ($azdValues.ContainsKey("SERVICENOW_OBO_CLIENT_SECRET")) { $azdValues["SERVICENOW_OBO_CLIENT_SECRET"] } else { $null }
$existingCopilotSecret = if ($azdValues.ContainsKey("COPILOT_STUDIO_CLIENT_SECRET")) { $azdValues["COPILOT_STUDIO_CLIENT_SECRET"] } else { $null }
$clientSecret = Get-OrCreateClientSecret -AppId $brokerApp.appId -DisplayName "servicenow-mcp-obo" -Years $SecretYears -ExistingSecret $existingBrokerSecret -Rotate:$RotateSecrets
$copilotStudioClientSecret = Get-OrCreateClientSecret -AppId $copilotStudioClientApp.appId -DisplayName "servicenow-mcp-copilot-studio" -Years $SecretYears -ExistingSecret $existingCopilotSecret -Rotate:$RotateSecrets
$tokenEndpoint = "https://login.microsoftonline.com/$TenantId/oauth2/v2.0/token"
$scopeValue = "$DownstreamIdentifierUri/.default"
$userScopeValue = "$BrokerIdentifierUri/$BrokerScopeName"
$copilotStudioScopeValue = "openid profile offline_access $userScopeValue"
$authorizationEndpoint = "https://login.microsoftonline.com/$TenantId/oauth2/v2.0/authorize"

$generatedValues = @{
    "SERVICENOW_OBO_TENANT_ID" = $TenantId
    "SERVICENOW_OBO_CLIENT_ID" = $brokerApp.appId
    "SERVICENOW_OBO_CLIENT_SECRET" = $clientSecret
    "SERVICENOW_OBO_SCOPE" = $scopeValue
    "SERVICENOW_OBO_PUBLIC_CLIENT_ID" = $interactiveClientApp.appId
    "SERVICENOW_OBO_USER_SCOPE" = $userScopeValue
    "SERVICENOW_OBO_TOKEN_ENDPOINT" = $tokenEndpoint
    "SERVICENOW_SN_JWT_TENANT_ID" = $TenantId
    "SERVICENOW_SN_JWT_UPSTREAM_CLIENT_ID" = $brokerApp.appId
    "COPILOT_STUDIO_TENANT_ID" = $TenantId
    "COPILOT_STUDIO_CLIENT_ID" = $copilotStudioClientApp.appId
    "COPILOT_STUDIO_CLIENT_SECRET" = $copilotStudioClientSecret
    "COPILOT_STUDIO_SCOPE" = $copilotStudioScopeValue
    "COPILOT_STUDIO_AUTHORIZATION_URL" = $authorizationEndpoint
    "COPILOT_STUDIO_TOKEN_URL" = $tokenEndpoint
    "COPILOT_STUDIO_REFRESH_URL" = $tokenEndpoint
}

if ($null -ne $CopilotStudioRedirectUris -and $CopilotStudioRedirectUris.Count -gt 0) {
    $generatedValues["COPILOT_STUDIO_REDIRECT_URI"] = $CopilotStudioRedirectUris[-1]
    $generatedValues["COPILOT_STUDIO_REDIRECT_URIS_JSON"] = ConvertTo-Json -InputObject @($CopilotStudioRedirectUris) -Compress
}

if ($ConfigureAzdEnvironment) {
    Set-AzdEnvironmentValues -Values $generatedValues
}
$repositoryRoot = Split-Path -Parent $PSScriptRoot
$localEnvPath = if ([System.IO.Path]::IsPathRooted($LocalEnvFile)) {
    $LocalEnvFile
} else {
    Join-Path -Path $repositoryRoot -ChildPath $LocalEnvFile
}
Update-LocalEnvFile -Path $localEnvPath -Values $generatedValues

Write-Host ""
Write-Host "Entra OBO bootstrap complete."
if ($ConfigureAzdEnvironment) {
    Write-Host "Generated Entra values were stored in the active azd environment and .env."
} else {
    Write-Host "Generated Entra values were stored in .env."
}
Write-Host "Generated values include secrets; values were not printed to the console."
